import { afterEach,describe,expect,it } from 'vitest';
import Dexie from 'dexie';
import { BurrowDatabase, loadSnapshot, saveSnapshot } from '@/lib/db';
import { DEFAULT_PREFERENCES, DEMO_OBJECTS, DEMO_ROOMS } from '@/lib/demo';

const databases:BurrowDatabase[]=[];
afterEach(async()=>{for(const db of databases){db.close();await db.delete();}databases.length=0;});
describe('local persistence',()=>{
  it('seeds an empty database and restores preferences',async()=>{const db=new BurrowDatabase(`test-${Math.random()}`);databases.push(db);const first=await loadSnapshot(db);expect(first.rooms).toHaveLength(3);first.preferences={...first.preferences,trayOpen:true,trayPinned:true};await saveSnapshot(first,db);const next=await loadSnapshot(db);expect(next.preferences.trayOpen).toBe(true);expect(next.preferences.trayPinned).toBe(true);});
  it('persists notes, favorites and bounded recent activity atomically',async()=>{const db=new BurrowDatabase(`test-${Math.random()}`);databases.push(db);const activity=Array.from({length:25},(_,i)=>({id:`a${i}`,objectId:DEMO_OBJECTS[0].id,name:'Search',url:DEMO_OBJECTS[0].url,openedAt:i}));await saveSnapshot({rooms:DEMO_ROOMS,objects:[{...DEMO_OBJECTS[0],favorite:true}],activity,note:'remember this',preferences:DEFAULT_PREFERENCES},db);const loaded=await loadSnapshot(db);expect(loaded.note).toBe('remember this');expect(loaded.objects[0].favorite).toBe(true);expect(loaded.activity).toHaveLength(20);});
  it('restores room ordering by creation time rather than IndexedDB key order',async()=>{const db=new BurrowDatabase(`test-${Math.random()}`);databases.push(db);await saveSnapshot({rooms:[...DEMO_ROOMS].reverse(),objects:[],activity:[],note:'',preferences:DEFAULT_PREFERENCES},db);const loaded=await loadSnapshot(db);expect(loaded.rooms.map(room=>room.id)).toEqual(DEMO_ROOMS.map(room=>room.id));});
  it('migrates incomplete legacy preferences to current defaults',async()=>{const name=`legacy-${Math.random()}`;const legacy=new Dexie(name);legacy.version(1).stores({rooms:'id,createdAt',objects:'id,roomId,url,favorite,createdAt',activity:'id,objectId,openedAt',settings:'key'});await legacy.open();await legacy.table('rooms').put(DEMO_ROOMS[0]);await legacy.table('settings').put({key:'preferences',value:{lastRoomId:'room-home'}});legacy.close();const migrated=new BurrowDatabase(name);databases.push(migrated);const loaded=await loadSnapshot(migrated);expect(loaded.preferences).toEqual({...DEFAULT_PREFERENCES,lastRoomId:'room-home'});});
  it('normalizes legacy collection labels and never persists session rooms',async()=>{const db=new BurrowDatabase(`session-${Math.random()}`);databases.push(db);const temporary={...DEMO_ROOMS[0],id:'session-room',lifecycle:'session' as const};await saveSnapshot({rooms:[...DEMO_ROOMS,temporary],objects:[...DEMO_OBJECTS,{...DEMO_OBJECTS[0],id:'session-object',roomId:temporary.id,lifecycle:'session'}],activity:[],note:'',preferences:DEFAULT_PREFERENCES},db);const loaded=await loadSnapshot(db);expect(loaded.rooms.some(room=>room.id===temporary.id)).toBe(false);expect(loaded.objects.some(object=>object.id==='session-object')).toBe(false);expect(loaded.collections.map(item=>item.name)).toEqual(expect.arrayContaining(['Everyday','Build','Unwind']));});
});
