'use client';

import { RoundedBox, Text } from '@react-three/drei';
import type { WorldWidgetViewModel } from '@/lib/integrations/contracts';
import { localAsset, threeText } from '@/lib/assets';

const FONT=localAsset('fonts/space-grotesk-latin-500-normal.woff');const MONO=localAsset('fonts/ibm-plex-mono-latin-500-normal.woff');
function Status({active,tone}:{active:boolean;tone:string}){return <group position={[.78,1.62,.48]}><mesh><sphereGeometry args={[.045,12,8]}/><meshStandardMaterial color={active?'#82d6b5':'#738096'} emissive={active?'#82d6b5':'#000'} emissiveIntensity={.25}/></mesh><mesh position={[0,0,-.02]}><cylinderGeometry args={[.08,.08,.025,16]}/><meshStandardMaterial color={tone} roughness={.8}/></mesh></group>}
function GithubTerminal({widget,near}:{widget:WorldWidgetViewModel;near:boolean}){return <group><RoundedBox args={[2.15,.18,1.05]} radius={.08} position={[0,.72,0]} castShadow><meshStandardMaterial color="#28323d" roughness={.82}/></RoundedBox><RoundedBox args={[2.05,1.35,.24]} radius={.12} position={[0,1.4,-.32]} castShadow><meshStandardMaterial color="#171d29" roughness={.72}/></RoundedBox><mesh position={[0,1.4,-.185]}><planeGeometry args={[1.72,1.02]}/><meshStandardMaterial color="#07100f" emissive={widget.tone} emissiveIntensity={near?.16:.08} roughness={.76}/></mesh><Text font={MONO} position={[-.72,1.75,-.16]} anchorX="left" fontSize={.08} color={widget.tone}>GITHUB / REPOSITORY</Text><Text font={FONT} position={[-.72,1.43,-.16]} anchorX="left" maxWidth={1.45} fontSize={.14} color="#f1f4fa">{threeText(widget.primary.slice(0,44))}</Text><Text font={MONO} position={[-.72,1.1,-.16]} anchorX="left" maxWidth={1.45} fontSize={.065} color="#8d9bae">{threeText(widget.secondary.slice(0,58))}</Text><mesh position={[0,.78,.12]}><cylinderGeometry args={[.09,.11,.38,12]}/><meshStandardMaterial color="#3d4654" roughness={.7}/></mesh><RoundedBox args={[.85,.08,.52]} radius={.04} position={[0,.56,.12]}><meshStandardMaterial color="#242b37" roughness={.82}/></RoundedBox><Status active={widget.active} tone={widget.tone}/></group>}
function Calendar({widget,near}:{widget:WorldWidgetViewModel;near:boolean}){return <group><RoundedBox args={[2.35,2.15,.2]} radius={.12} position={[0,1.35,0]} castShadow><meshStandardMaterial color="#36343f" roughness={.94}/></RoundedBox><RoundedBox args={[2.06,1.78,.06]} radius={.06} position={[0,1.28,.14]}><meshStandardMaterial color="#ddd7ca" roughness={1}/></RoundedBox><RoundedBox args={[2.06,.38,.07]} radius={.05} position={[0,2,.15]}><meshStandardMaterial color={near?widget.tone:'#6e6d88'} roughness={.85}/></RoundedBox>{[-.72,0,.72].map(x=><mesh key={x} position={[x,2.18,.17]}><torusGeometry args={[.07,.018,8,18]}/><meshStandardMaterial color="#aeb2be" roughness={.7}/></mesh>)}<Text font={MONO} position={[-.85,1.84,.18]} anchorX="left" fontSize={.07} color="#343846">UP NEXT</Text><Text font={FONT} position={[-.85,1.48,.18]} anchorX="left" maxWidth={1.7} fontSize={.15} color="#252a36">{threeText(widget.primary.slice(0,50))}</Text><Text font={MONO} position={[-.85,1.02,.18]} anchorX="left" maxWidth={1.7} fontSize={.065} color="#626879">{threeText(widget.secondary.slice(0,62))}</Text>{[-.72,-.24,.24,.72].map((x,i)=><RoundedBox key={x} args={[.3,.24,.025]} radius={.035} position={[x,.67,.19]}><meshStandardMaterial color={i===0?widget.tone:'#c8c5bd'} roughness={1}/></RoundedBox>)}</group>}
function FeedRack({widget,near}:{widget:WorldWidgetViewModel;near:boolean}){return <group><RoundedBox args={[2.4,.36,1.35]} radius={.14} position={[0,.25,0]} castShadow><meshStandardMaterial color="#2b313d" roughness={.9}/></RoundedBox>{[-.72,0,.72].map((x,i)=><group key={x} position={[x,.86,-i*.05]} rotation={[0,0,(i-1)*.05]}><RoundedBox args={[.68,1.25,.09]} radius={.05} castShadow><meshStandardMaterial color={i===1?'#d5cfbf':'#b7bdc4'} roughness={1}/></RoundedBox><mesh position={[0,.25,.055]}><planeGeometry args={[.5,.12]}/><meshBasicMaterial color={i===0?widget.tone:'#4d5668'}/></mesh>{[-.08,.08].map(y=><mesh key={y} position={[0,y-.12,.056]}><planeGeometry args={[.48,.025]}/><meshBasicMaterial color="#747b84"/></mesh>)}</group>)}<RoundedBox args={[2.25,.18,.18]} radius={.06} position={[0,.5,.58]}><meshStandardMaterial color={near?widget.tone:'#596274'} roughness={.82}/></RoundedBox><Text font={MONO} position={[0,1.68,.1]} fontSize={.08} color={widget.tone}>LIVE FEEDS</Text><Text font={FONT} position={[0,1.45,.1]} maxWidth={2} fontSize={.12} color="#e7ebf2">{threeText(widget.primary.slice(0,48))}</Text></group>}
function WeatherSensor({widget,near}:{widget:WorldWidgetViewModel;near:boolean}){return <group><RoundedBox args={[1.85,1.15,.72]} radius={.18} position={[0,.75,0]} castShadow><meshStandardMaterial color="#242d3b" roughness={.88}/></RoundedBox><RoundedBox args={[1.5,.7,.06]} radius={.08} position={[0,.82,.39]}><meshStandardMaterial color="#0e1823" emissive={widget.tone} emissiveIntensity={near ? .14 : .06} roughness={.82}/></RoundedBox><Text font={MONO} position={[0,1.04,.43]} fontSize={.065} color={widget.tone}>OUTSIDE</Text><Text font={FONT} position={[0,.78,.43]} fontSize={.16} maxWidth={1.3} color="#eef3fa">{threeText(widget.primary.slice(0,30))}</Text><Text font={MONO} position={[0,.55,.43]} fontSize={.055} maxWidth={1.3} color="#8795a8">{threeText(widget.secondary.slice(0,38))}</Text><mesh position={[-.56,.2,0]}><cylinderGeometry args={[.06,.09,.4,12]}/><meshStandardMaterial color="#485364" roughness={.8}/></mesh><mesh position={[.56,.2,0]}><cylinderGeometry args={[.06,.09,.4,12]}/><meshStandardMaterial color="#485364" roughness={.8}/></mesh></group>}

export function LiveWidget({widget,position,rotation=0,near}:{widget:WorldWidgetViewModel;position:[number,number,number];rotation?:number;near:boolean}) {return <group position={position} rotation={[0,rotation,0]} userData={{interactionId:`__live:${widget.id}`}}>{widget.kind==='github-repo'?<GithubTerminal widget={widget} near={near}/>:widget.kind==='calendar'?<Calendar widget={widget} near={near}/>:widget.kind==='feed'?<FeedRack widget={widget} near={near}/>:<WeatherSensor widget={widget} near={near}/>}</group>}
