'use client';

import { create } from 'zustand';
import { DEFAULT_PREFERENCES, DEMO_OBJECTS, DEMO_ROOMS } from '@/lib/demo';
import { loadSnapshot, saveSnapshot, type Snapshot } from '@/lib/db';
import { mergeConfig } from '@/lib/config';
import type { Activity, Archetype, BookmarkObject, ConfigEnvelopeV1, ModalName, Preferences, Room, RoomTemplate } from '@/lib/types';
import { autoArchetype, normalizeUrl, safeOpen } from '@/lib/url';
import type { ParsedBookmark } from '@/lib/bookmarks';
import { firstValidPlacement, validatePlacement } from '@/lib/placement';

type SiteInput={name:string;url:string;roomId:string;archetype:Archetype;color:string;favorite:boolean;collection?:string;note?:string};
type BurrowState={
  ready:boolean; rooms:Room[]; objects:BookmarkObject[]; activity:Activity[]; note:string; preferences:Preferences;
  currentRoomId:string; modal:ModalName; launcherOpen:boolean; editMode:boolean; selectedId:string|null; nearObjectId:string|null;
  toast:string|null; teleportNonce:number; teleportTarget:[number,number,number]; undoObject:BookmarkObject|null; openPulse:{id:string;nonce:number}|null;
  initialize:()=>Promise<void>; openModal:(modal:ModalName,id?:string)=>void; setLauncher:(open:boolean)=>void; setToast:(message:string|null)=>void;
  setEntered:(value:boolean)=>void; setCurrentRoom:(id:string)=>void; createRoom:(name:string,template:RoomTemplate,accent:string)=>void; renameRoom:(id:string,name:string)=>void; deleteRoom:(id:string)=>void;
  addSite:(input:SiteInput)=>void; updateSite:(id:string,input:Partial<SiteInput>)=>void; duplicateSite:(id:string)=>void; deleteSite:(id:string)=>void; openSite:(id:string)=>void;
  setFavorite:(id:string,value:boolean)=>void; setSelected:(id:string|null)=>void; setNearObject:(id:string|null)=>void; setEditMode:(value:boolean)=>void;
  beginObjectEdit:(id:string)=>void; placeObject:(id:string,position:[number,number,number])=>void; rotateObject:(id:string,delta:number)=>void; resetObjectPlacement:(id:string)=>void; undoLastEdit:()=>void;
  teleport:(target:[number,number,number])=>void; returnToSpawn:()=>void; setTrayOpen:(value:boolean)=>void; setTrayPinned:(value:boolean)=>void; setReducedEffects:(value:boolean)=>void; setNote:(note:string)=>void;
  rememberSearch:(query:string)=>void;
  importBookmarks:(items:{bookmark:ParsedBookmark;roomId:string}[],keepBoth:boolean)=>{added:number;skipped:number}; applyConfig:(config:ConfigEnvelopeV1,mode:'merge'|'replace')=>void;
  resetAll:(withDemo:boolean)=>void; clearDemo:()=>void;
};

function snapshot(state:BurrowState):Snapshot { return {rooms:state.rooms,objects:state.objects,activity:state.activity,note:state.note,preferences:state.preferences}; }
let saveTimer:ReturnType<typeof setTimeout>|undefined;
let initializeTask:Promise<void>|undefined;
function scheduleSave(get:()=>BurrowState) { clearTimeout(saveTimer); saveTimer=setTimeout(()=>void saveSnapshot(snapshot(get())),120); }
function placementFor(index:number):[number,number,number] { const slots:[number,number,number][]=[[-5,0,-3],[-2,0,-4],[2,0,-4],[5,0,-3],[-5,0,1],[-2,0,2],[2,0,2],[5,0,1]]; return slots[index%slots.length]; }

export const useBurrow=create<BurrowState>((set,get)=>({
  ready:false,rooms:[],objects:[],activity:[],note:'',preferences:DEFAULT_PREFERENCES,currentRoomId:'room-home',modal:null,launcherOpen:false,editMode:false,selectedId:null,nearObjectId:null,toast:null,teleportNonce:0,teleportTarget:[0,1.1,7],undoObject:null,openPulse:null,
  initialize:async()=>{if(get().ready)return;if(initializeTask)return initializeTask;initializeTask=(async()=>{try{const data=await loadSnapshot();const roomId=data.rooms.some(r=>r.id===data.preferences.lastRoomId)?data.preferences.lastRoomId:data.rooms[0]?.id||'room-home';set({...data,currentRoomId:roomId,ready:true});}catch{set({rooms:structuredClone(DEMO_ROOMS),objects:structuredClone(DEMO_OBJECTS),preferences:DEFAULT_PREFERENCES,currentRoomId:'room-home',ready:true,toast:'Local storage was repaired with the starter Burrow.'});}finally{initializeTask=undefined;}})();return initializeTask;},
  openModal:(modal,id)=>set({modal,selectedId:id??get().selectedId,launcherOpen:false}),setLauncher:(launcherOpen)=>set({launcherOpen,modal:launcherOpen?null:get().modal}),setToast:(toast)=>set({toast}),
  setEntered:(value)=>{set(s=>({preferences:{...s.preferences,hasEntered:value}}));scheduleSave(get);},
  setCurrentRoom:(id)=>{const room=get().rooms.find(r=>r.id===id);if(!room)return;set(s=>({currentRoomId:id,preferences:{...s.preferences,lastRoomId:id},selectedId:null,nearObjectId:null,editMode:false,teleportTarget:room.spawn,teleportNonce:s.teleportNonce+1,toast:`Arrived in ${room.name}`}));scheduleSave(get);},
  createRoom:(name,template,accent)=>{const id=crypto.randomUUID();const room:Room={id,name:name.trim()||'Untitled room',template,accent,spawn:[0,1.1,7],isDemo:false,createdAt:Date.now()};set(s=>({rooms:[...s.rooms,room],modal:null,toast:`Created ${room.name}`}));scheduleSave(get);get().setCurrentRoom(id);},
  renameRoom:(id,name)=>{set(s=>({rooms:s.rooms.map(r=>r.id===id?{...r,name:name.trim()||r.name}:r)}));scheduleSave(get);},
  deleteRoom:(id)=>{const state=get();if(state.rooms.length<=1){set({toast:'A Burrow needs at least one room.'});return;}const destination=state.rooms.find(r=>r.id!==id)!;set(s=>({rooms:s.rooms.filter(r=>r.id!==id),objects:s.objects.map((o,index)=>o.roomId===id?{...o,roomId:destination.id,position:placementFor(index),updatedAt:Date.now()}:o),currentRoomId:s.currentRoomId===id?destination.id:s.currentRoomId,selectedId:null,toast:`Room removed. Its sites moved to ${destination.name}.`}));scheduleSave(get);},
  addSite:(input)=>{let url:string;try{url=normalizeUrl(input.url);}catch(error){set({toast:error instanceof Error?error.message:'Invalid URL'});return;}const archetype=input.archetype||autoArchetype(url);const position=firstValidPlacement(input.roomId,archetype,get().objects);const object:BookmarkObject={id:crypto.randomUUID(),roomId:input.roomId,name:input.name.trim()||new URL(url).hostname,url,archetype,icon:'globe',color:input.color,position,rotation:0,favorite:input.favorite,usageCount:0,collection:input.collection?.trim()||undefined,note:input.note?.trim()||undefined,source:'manual',isDemo:false,createdAt:Date.now(),updatedAt:Date.now()};set(s=>({objects:[...s.objects,object],modal:null,selectedId:object.id,toast:`${object.name} has a place in your Burrow.`}));scheduleSave(get);},
  updateSite:(id,input)=>{try{set(s=>({objects:s.objects.map(o=>{if(o.id!==id)return o;const roomChanged=input.roomId&&input.roomId!==o.roomId;const archetype=input.archetype??o.archetype;return {...o,...input,url:input.url?normalizeUrl(input.url):o.url,name:input.name?.trim()||o.name,collection:input.collection?.trim()||undefined,note:input.note?.trim()||undefined,position:roomChanged?firstValidPlacement(input.roomId!,archetype,s.objects):o.position,updatedAt:Date.now()};}),modal:null,toast:'Website updated.'}));scheduleSave(get);}catch(error){set({toast:error instanceof Error?error.message:'Could not update website.'});}},
  duplicateSite:(id)=>{const source=get().objects.find(o=>o.id===id);if(!source)return;const copy:BookmarkObject={...structuredClone(source),id:crypto.randomUUID(),name:`${source.name} copy`,position:firstValidPlacement(source.roomId,source.archetype,get().objects),favorite:false,isDemo:false,source:'manual',usageCount:0,createdAt:Date.now(),updatedAt:Date.now()};set(s=>({objects:[...s.objects,copy],selectedId:copy.id,undoObject:null,toast:`Duplicated ${source.name}.`}));scheduleSave(get);},
  deleteSite:(id)=>{const name=get().objects.find(o=>o.id===id)?.name;set(s=>({objects:s.objects.filter(o=>o.id!==id),selectedId:null,modal:null,toast:name?`${name} removed.`:'Website removed.'}));scheduleSave(get);},
  openSite:(id)=>{const object=get().objects.find(o=>o.id===id);if(!object)return;safeOpen(object.url);const item:Activity={id:crypto.randomUUID(),objectId:id,name:object.name,url:object.url,openedAt:Date.now()};set(s=>({objects:s.objects.map(o=>o.id===id?{...o,usageCount:o.usageCount+1}:o),activity:[item,...s.activity.filter(a=>a.objectId!==id)].slice(0,20),openPulse:{id,nonce:(s.openPulse?.nonce??0)+1},toast:`Opening ${object.name}…`}));scheduleSave(get);},
  setFavorite:(id,value)=>{set(s=>({objects:s.objects.map(o=>o.id===id?{...o,favorite:value,updatedAt:Date.now()}:o)}));scheduleSave(get);},setSelected:(selectedId)=>set({selectedId}),setNearObject:(nearObjectId)=>set({nearObjectId}),setEditMode:(editMode)=>set({editMode,selectedId:null,nearObjectId:null}),
  beginObjectEdit:(id)=>{const object=get().objects.find(o=>o.id===id);if(object)set({undoObject:structuredClone(object),selectedId:id});},
  placeObject:(id,position)=>{const object=get().objects.find(o=>o.id===id);if(!object)return;const result=validatePlacement(object,position,get().objects.filter(o=>o.roomId===object.roomId));if(!result.valid){set({toast:result.reason??'That placement is blocked.'});return;}set(s=>({objects:s.objects.map(o=>o.id===id?{...o,position:result.position,updatedAt:Date.now()}:o),toast:null}));scheduleSave(get);},
  rotateObject:(id,delta)=>{const original=get().objects.find(o=>o.id===id);if(original&&!get().undoObject)set({undoObject:structuredClone(original)});set(s=>({objects:s.objects.map(o=>o.id===id?{...o,rotation:o.rotation+delta,updatedAt:Date.now()}:o)}));scheduleSave(get);},
  resetObjectPlacement:(id)=>{const object=get().objects.find(o=>o.id===id);if(!object)return;get().beginObjectEdit(id);const position=firstValidPlacement(object.roomId,object.archetype,get().objects.filter(o=>o.id!==id));set(s=>({objects:s.objects.map(o=>o.id===id?{...o,position,updatedAt:Date.now()}:o),toast:`${object.name} reset to a safe placement.`}));scheduleSave(get);},
  undoLastEdit:()=>{const undo=get().undoObject;if(!undo){set({toast:'Nothing to undo yet.'});return;}set(s=>({objects:s.objects.map(o=>o.id===undo.id?undo:o),undoObject:null,toast:'Last object edit undone.'}));scheduleSave(get);},
  teleport:(target)=>set(s=>({teleportTarget:target,teleportNonce:s.teleportNonce+1})),returnToSpawn:()=>{const room=get().rooms.find(r=>r.id===get().currentRoomId);if(room)get().teleport(room.spawn);set({toast:'Back at a safe spot.'});},
  setTrayOpen:(trayOpen)=>{set(s=>({preferences:{...s.preferences,trayOpen}}));scheduleSave(get);},setTrayPinned:(trayPinned)=>{set(s=>({preferences:{...s.preferences,trayPinned,trayOpen:trayPinned||s.preferences.trayOpen}}));scheduleSave(get);},setReducedEffects:(reducedEffects)=>{set(s=>({preferences:{...s.preferences,reducedEffects}}));scheduleSave(get);},setNote:(note)=>{set({note:note.slice(0,5000)});scheduleSave(get);},
  rememberSearch:(query)=>{const value=query.trim();if(!value)return;set(s=>({preferences:{...s.preferences,recentSearches:[value,...s.preferences.recentSearches.filter(item=>item!==value)].slice(0,6)}}));scheduleSave(get);},
  importBookmarks:(items,keepBoth)=>{const state=get();const existing=new Set(state.objects.map(o=>o.url));let skipped=0;const added:BookmarkObject[]=[];for(const {bookmark,roomId} of items){if(!bookmark.selected)continue;if(existing.has(bookmark.url)&&!keepBoth){skipped++;continue;}const archetype=autoArchetype(bookmark.url);const working=[...state.objects,...added];added.push({id:crypto.randomUUID(),roomId,name:bookmark.title,url:bookmark.url,archetype,icon:'globe',color:'#8be6ff',position:firstValidPlacement(roomId,archetype,working),rotation:0,favorite:false,usageCount:0,collection:bookmark.folderPath.at(-1),source:'bookmark-html',isDemo:false,createdAt:Date.now(),updatedAt:Date.now()});existing.add(bookmark.url);}set(s=>({objects:[...s.objects,...added],modal:null,toast:`Imported ${added.length} bookmark${added.length===1?'':'s'}${skipped?`; skipped ${skipped} duplicate${skipped===1?'':'s'}`:''}.`}));scheduleSave(get);return{added:added.length,skipped};},
  applyConfig:(config,mode)=>{const current=snapshot(get());const next=mode==='merge'?mergeConfig(current,config):{rooms:config.rooms,objects:config.objects,activity:config.activity,note:config.note,preferences:config.preferences};const roomId=next.rooms.some(r=>r.id===next.preferences.lastRoomId)?next.preferences.lastRoomId:next.rooms[0]?.id;if(!roomId){set({toast:'That configuration does not contain a room.'});return;}set({...next,currentRoomId:roomId,modal:null,selectedId:null,toast:mode==='merge'?'Configuration merged.':'Configuration replaced.'});scheduleSave(get);},
  resetAll:(withDemo)=>{const rooms=withDemo?structuredClone(DEMO_ROOMS):[{id:crypto.randomUUID(),name:'My Burrow',template:'den' as const,accent:'#a78bfa',spawn:[0,1.1,7] as [number,number,number],isDemo:false,createdAt:Date.now()}];const objects=withDemo?structuredClone(DEMO_OBJECTS):[];const preferences={...DEFAULT_PREFERENCES,lastRoomId:rooms[0].id,hasEntered:true};set({rooms,objects,activity:[],note:'',preferences,currentRoomId:rooms[0].id,modal:null,selectedId:null,toast:withDemo?'Starter Burrow restored.':'Fresh Burrow ready.'});scheduleSave(get);},
  clearDemo:()=>{set(s=>({objects:s.objects.filter(o=>!o.isDemo),rooms:s.rooms.map(r=>({...r,isDemo:false})),toast:'Demo websites cleared. Your rooms remain.'}));scheduleSave(get);},
}));
