'use client';

import { useEffect, useState } from 'react';
import { Compass, Diamond, Edit3, HelpCircle, Plus, RotateCcw, Search, Sparkles, X } from 'lucide-react';
import { BurrowWorld } from './world/burrow-world';
import { BurrowTray } from './burrow-tray';
import { CommandLauncher, EditPanel, ModalLayer } from './overlays';
import { useBurrow } from '@/store/use-burrow';

export function WebBurrowApp() {
  const ready=useBurrow(s=>s.ready);const initialize=useBurrow(s=>s.initialize);const currentRoom=useBurrow(s=>s.rooms.find(r=>r.id===s.currentRoomId));const nearId=useBurrow(s=>s.nearObjectId);const nearObject=useBurrow(s=>s.objects.find(o=>o.id===s.nearObjectId));const preferences=useBurrow(s=>s.preferences);const setEntered=useBurrow(s=>s.setEntered);const openModal=useBurrow(s=>s.openModal);const setLauncher=useBurrow(s=>s.setLauncher);const editMode=useBurrow(s=>s.editMode);const setEditMode=useBurrow(s=>s.setEditMode);const setTrayOpen=useBurrow(s=>s.setTrayOpen);const returnToSpawn=useBurrow(s=>s.returnToSpawn);const toast=useBurrow(s=>s.toast);const setToast=useBurrow(s=>s.setToast);const [locked,setLocked]=useState(false);const [compactNotice,setCompactNotice]=useState(false);
  useEffect(()=>{void initialize();},[initialize]);
  useEffect(()=>{const check=()=>setCompactNotice(innerWidth<720||innerHeight<520);check();window.addEventListener('resize',check);return()=>window.removeEventListener('resize',check);},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;const typing=target?.matches('input,textarea,select,[contenteditable=true]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setLauncher(true);return;}if(!typing&&e.key==='/'){e.preventDefault();setLauncher(true);}if(!typing&&e.key.toLowerCase()==='t'){setTrayOpen(!useBurrow.getState().preferences.trayOpen);}if(!typing&&e.key.toLowerCase()==='r'&&e.altKey)returnToSpawn();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[returnToSpawn,setLauncher,setTrayOpen]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),3200);return()=>clearTimeout(id);},[setToast,toast]);
  const enter=()=>{setEntered(true);const request=document.querySelector('canvas')?.requestPointerLock();if(request)void request.catch(()=>setToast('Mouse look is unavailable here. Quick Access still works.'));};
  if(!ready)return <main className="grid h-dvh w-screen place-items-center bg-[#080913]"><div className="text-center"><span className="burrow-loader mx-auto mb-4 block h-11 w-11 rounded-2xl border border-violet-300/30 bg-violet-300/10"/><p className="mono text-[10px] uppercase tracking-[.25em] text-white/38">Opening your Burrow</p></div></main>;
  return <main className="relative h-dvh w-screen overflow-hidden bg-[#080913]">
    <div id="world-surface" className="absolute inset-0"><BurrowWorld onLockChange={setLocked}/></div>
    <header className="pointer-events-none absolute inset-x-0 top-0 z-10 flex items-start justify-between gap-3 p-4 md:p-6"><button onClick={()=>openModal('data')} className="glass pointer-events-auto flex items-center gap-3 rounded-2xl px-3 py-2.5 text-left transition hover:-translate-y-0.5 md:px-4 md:py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-400/15 text-violet-200"><Diamond size={19}/></span><span className="min-w-0"><span className="block text-[9px] font-semibold uppercase tracking-[.22em] text-violet-200/55">WebBurrow</span><span className="block max-w-36 truncate text-sm font-medium">{currentRoom?.name}</span></span></button><nav className="pointer-events-auto flex gap-2" aria-label="Primary actions"><button onClick={()=>openModal('add-site')} className="hud-button" aria-label="Add website"><Plus size={17}/><span className="hidden lg:inline">Add site</span></button><button onClick={()=>setLauncher(true)} className="hud-button" aria-label="Open Quick Access"><Search size={17}/><span className="hidden sm:inline">Quick Access</span><kbd className="mono hidden rounded bg-white/8 px-1.5 py-0.5 text-[9px] text-white/42 md:inline">Ctrl K</kbd></button><button onClick={()=>{document.exitPointerLock?.();setEditMode(!editMode);}} className={`hud-button ${editMode?'!border-cyan-200/40 !bg-cyan-200/10 text-cyan-100':''}`} aria-pressed={editMode}><Edit3 size={17}/><span className="hidden xl:inline">Edit</span></button><button onClick={()=>openModal('help')} className="hud-button" aria-label="Help"><HelpCircle size={17}/></button></nav></header>

    {!preferences.hasEntered&&!editMode&&<section className="glass absolute left-1/2 top-1/2 z-20 w-[min(470px,calc(100%-32px))] -translate-x-1/2 -translate-y-1/2 rounded-[28px] p-7 text-center md:p-8"><span className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-200"><Sparkles size={22}/></span><p className="mono mb-2 text-[10px] uppercase tracking-[.24em] text-cyan-200/70">Your internet is a place</p><h1 className="m-0 text-3xl font-semibold tracking-[-.045em] md:text-4xl">Enter your {currentRoom?.name||'Burrow'}</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-white/57">Walk up to the objects that make up your digital life—or open anything instantly.</p><button id="explore-trigger" onClick={enter} className="mt-6 rounded-xl bg-[#ddd6ff] px-5 py-3 text-sm font-semibold text-[#171529] shadow-[0_8px_30px_rgba(139,117,255,.28)]">Click to explore</button><div className="mono mt-5 flex flex-wrap justify-center gap-x-4 gap-y-1 text-[9px] uppercase tracking-wider text-white/34"><span>WASD Move</span><span>Mouse Look</span><span>E Use</span><span>Ctrl K Search</span></div><button onClick={()=>setEntered(true)} className="mt-4 text-xs text-white/34 underline decoration-white/15 underline-offset-4">Skip walking and use the interface</button></section>}

    {locked&&!editMode&&<div className="pointer-events-none absolute left-1/2 top-1/2 h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/70 bg-white/15 shadow-[0_0_10px_rgba(139,230,255,.7)]"/>}
    {!editMode&&preferences.hasEntered&&<div className={`interaction-prompt pointer-events-none absolute bottom-6 left-1/2 z-10 flex -translate-x-1/2 items-center gap-2 rounded-full px-4 py-2 text-xs glass ${nearId?'is-active':''}`}><Compass size={14} className="text-cyan-200"/><span>{nearId==='__portal'?'Enter the Burrow Lift':nearObject?`Open ${nearObject.name}`:'Face an object to interact'}</span>{nearId&&<span className="mono ml-2 rounded bg-white/10 px-2 py-1 text-[10px]">E</span>}</div>}
    <button onClick={returnToSpawn} className="glass absolute bottom-6 left-6 z-10 hidden items-center gap-2 rounded-xl px-3 py-2 text-xs text-white/48 md:flex" title="Return to a safe spot (Home key)"><RotateCcw size={13}/>Safe spot</button>
    <EditPanel/><BurrowTray/><CommandLauncher/><ModalLayer/>
    {toast&&<div role="status" className="toast glass absolute left-1/2 top-24 z-50 -translate-x-1/2 rounded-xl px-4 py-2.5 text-sm shadow-xl">{toast}</div>}
    {compactNotice&&<div className="absolute inset-x-3 bottom-3 z-50 flex items-start gap-3 rounded-xl border border-amber-100/16 bg-[#17121e]/95 p-3 text-xs text-amber-50 shadow-xl md:hidden"><span className="min-w-0 flex-1">WebBurrow plays best with a keyboard, mouse, and a little more room. Quick Access and the tray still work here.</span><button onClick={()=>setCompactNotice(false)} aria-label="Dismiss"><X size={15}/></button></div>}
  </main>;
}
