'use client';

import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Compass, Diamond, Edit3, HelpCircle, Plus, RotateCcw, Search, Sparkles, X } from 'lucide-react';
import { BurrowTray } from './burrow-tray';
import { CommandLauncher, EditPanel, ModalLayer } from './overlays';
import { useBurrow } from '@/store/use-burrow';
import { applyAudioPreferences, handleAudioVisibility, playAudioCue } from '@/lib/audio';
import type { Preferences } from '@/lib/types';
import { recordBrowserArrival, recordReactRender, setPerformanceHidden } from '@/lib/performance';

const BurrowWorld=lazy(()=>import('./world/burrow-world').then(module=>({default:module.BurrowWorld})));
type Milestone=Preferences['onboardingMilestones'][number];
const GUIDANCE:{id:Exclude<Milestone,'enter'>;title:string;body:string;key:string}[]=[
  {id:'move',title:'Take a few steps',body:'Use WASD to move. Shift gives you a gentle sprint and Space jumps.',key:'WASD'},
  {id:'interact',title:'Use what you see',body:'Face a glowing object and press E. Every important action is also available in the interface.',key:'E'},
  {id:'quick-access',title:'Everything is one search away',body:'Quick Access searches sites, rooms, sessions, live data, commands, and the web.',key:'Ctrl K'},
  {id:'tray',title:'Carry a pocket view',body:'The Burrow Tray keeps Mini Burrow, favorites, notes, and live cards close.',key:'T'},
  {id:'portal',title:'Rooms are connected',body:'Use the Burrow Lift or choose any room from Quick Access and Mini Burrow.',key:'Lift'},
  {id:'edit',title:'Make the space yours',body:'Edit mode uses the shared room layout to snap objects onto safe floors, desks, shelves, and walls.',key:'Edit'},
  {id:'add-site',title:'Give a site a place',body:'Add any HTTP or HTTPS destination and choose its room, collection, object, and color.',key:'Add'},
  {id:'companion',title:'Optional browser companion',body:'The unpacked Chromium companion can send pages, selected tabs, a window, a group, or bookmark previews.',key:'Optional'},
];

export function WebBurrowApp() {
  recordReactRender('WebBurrowApp');
  const ready=useBurrow(s=>s.ready);const initialize=useBurrow(s=>s.initialize);const rooms=useBurrow(s=>s.rooms);const currentRoom=useBurrow(s=>s.rooms.find(r=>r.id===s.currentRoomId));const nearId=useBurrow(s=>s.nearObjectId);const nearObject=useBurrow(s=>s.objects.find(o=>o.id===s.nearObjectId));const openPulse=useBurrow(s=>s.openPulse);const preferences=useBurrow(s=>s.preferences);const setEntered=useBurrow(s=>s.setEntered);const completeOnboarding=useBurrow(s=>s.completeOnboarding);const openModal=useBurrow(s=>s.openModal);const setLauncher=useBurrow(s=>s.setLauncher);const setCurrentRoom=useBurrow(s=>s.setCurrentRoom);const editMode=useBurrow(s=>s.editMode);const setEditMode=useBurrow(s=>s.setEditMode);const setTrayOpen=useBurrow(s=>s.setTrayOpen);const returnToSpawn=useBurrow(s=>s.returnToSpawn);const toast=useBurrow(s=>s.toast);const setToast=useBurrow(s=>s.setToast);const [locked,setLocked]=useState(false);const [compactNotice,setCompactNotice]=useState(false);const [arrival,setArrival]=useState<string|null>(null);const previousRoom=useRef<string|null>(null);
  useEffect(()=>{void initialize();},[initialize]);
  useEffect(()=>{const check=()=>setCompactNotice(innerWidth<720||innerHeight<520);check();window.addEventListener('resize',check);return()=>window.removeEventListener('resize',check);},[]);
  useEffect(()=>{if(!ready)return;const refresh=useBurrow.getState().refreshDue;void refresh();const timer=window.setInterval(()=>{if(!document.hidden)void refresh();},60_000);const online=()=>void refresh();const visibility=()=>{setPerformanceHidden(document.hidden);if(!document.hidden)void refresh();};setPerformanceHidden(document.hidden);window.addEventListener('online',online);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);window.removeEventListener('online',online);document.removeEventListener('visibilitychange',visibility);};},[ready]);
  useEffect(()=>{if(!ready||!window.webburrowDesktop)return;const sync=()=>{const state=useBurrow.getState();window.webburrowDesktop?.setTrayPreferences({enabled:state.preferences.systemTrayEnabled,minimizeToTray:state.preferences.minimizeToTray});window.webburrowDesktop?.syncTrayMenu({favorites:state.objects.filter(item=>item.favorite).slice(0,8).map(item=>({id:item.id,name:item.name,url:item.url})),recent:state.activity.slice(0,8).map(item=>({id:item.id,name:item.name,url:item.url}))});window.webburrowDesktop?.syncBrowserContext({workspaces:state.browserWorkspaces.map(workspace=>({id:workspace.id,name:workspace.name,tabCount:state.objects.filter(item=>item.browserReference?.workspaceId===workspace.id).length,sourceScope:workspace.sourceScope})),rooms:state.rooms.filter(room=>room.lifecycle==='permanent').map(room=>({id:room.id,name:room.name})),collections:state.collections.filter(collection=>collection.lifecycle==='permanent').map(collection=>({id:collection.id,name:collection.name}))});};sync();const unsubscribe=useBurrow.subscribe(sync);const stop=window.webburrowDesktop.onCommand(command=>{const state=useBurrow.getState();if(command.type==='quick-access')state.setLauncher(true);else if(command.type==='add'){const payload=command.payload as {title?:unknown;url?:unknown}|undefined;useBurrow.setState({pendingSitePrefill:{name:typeof payload?.title==='string'?payload.title:'',url:typeof payload?.url==='string'?payload.url:''},modal:'add-site'});}else if(command.type==='toggle-tray')state.setTrayOpen(!state.preferences.trayOpen);else if(command.type==='favorites'||command.type==='recent')state.setLauncher(true);else if(command.type==='room'&&typeof command.payload==='string')state.setCurrentRoom(command.payload);else if(command.type==='open-object'&&typeof command.payload==='string')state.openSite(command.payload);else if(command.type==='browser-page'&&command.payload&&typeof command.payload==='object'){state.receiveBrowserPage(command.payload as Parameters<typeof state.receiveBrowserPage>[0]);state.completeOnboarding('companion');}else if(command.type==='browser-tabs'&&command.payload&&typeof command.payload==='object'){const payload=command.payload as {name:string;tabs:Parameters<typeof state.receiveBrowserTabs>[1];options?:Parameters<typeof state.receiveBrowserTabs>[2]};const started=performance.now();state.receiveBrowserTabs(payload.name,payload.tabs,payload.options);recordBrowserArrival(performance.now()-started);state.completeOnboarding('companion');}else if(command.type==='bookmark-preview'&&typeof command.payload==='string'){useBurrow.setState({pendingBookmarkHtml:command.payload,modal:'import-bookmarks'});state.completeOnboarding('companion');}else if(command.type==='visibility'&&command.payload===true)void state.refreshDue();});return()=>{unsubscribe();stop();};},[ready]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target,typing=target instanceof HTMLElement&&target.matches('input,textarea,select,[contenteditable=true]');const openQuickAccess=()=>{document.exitPointerLock?.();setLauncher(true);completeOnboarding('quick-access');playAudioCue('ui',useBurrow.getState().preferences);};if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openQuickAccess();return;}if(!typing&&e.key==='/'){e.preventDefault();openQuickAccess();}if(!typing&&['KeyW','KeyA','KeyS','KeyD'].includes(e.code))completeOnboarding('move');if(!typing&&e.code==='KeyE'&&useBurrow.getState().nearObjectId)completeOnboarding('interact');if(!typing&&e.key.toLowerCase()==='t'){document.exitPointerLock?.();setTrayOpen(!useBurrow.getState().preferences.trayOpen);completeOnboarding('tray');playAudioCue('ui',useBurrow.getState().preferences);}if(!typing&&e.key==='Home')returnToSpawn();if(!typing&&e.altKey&&/^Digit[123]$/.test(e.code)){const room=rooms[Number(e.code.at(-1))-1];if(room)setCurrentRoom(room.id);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[completeOnboarding,returnToSpawn,rooms,setCurrentRoom,setLauncher,setTrayOpen]);
  useEffect(()=>{if(!currentRoom)return;if(previousRoom.current&&previousRoom.current!==currentRoom.id){setArrival(currentRoom.name);completeOnboarding('portal');playAudioCue('portal',preferences);const id=window.setTimeout(()=>setArrival(null),900);previousRoom.current=currentRoom.id;return()=>clearTimeout(id);}previousRoom.current=currentRoom.id;},[completeOnboarding,currentRoom,preferences]);
  useEffect(()=>{if(openPulse){completeOnboarding('interact');playAudioCue('open',preferences);}},[completeOnboarding,openPulse,preferences]);
  useEffect(()=>{const visibility=()=>handleAudioVisibility(useBurrow.getState().preferences);document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),3200);return()=>clearTimeout(id);},[setToast,toast]);
  const enter=()=>{setEntered(true);completeOnboarding('enter');void applyAudioPreferences(preferences,true).then(()=>playAudioCue('interaction',preferences));const request=document.querySelector('#world-surface canvas')?.requestPointerLock();if(request)void request.catch(()=>setToast('Mouse look is unavailable here. Quick Access still works.'));};
  const useInterface=()=>{setEntered(true);completeOnboarding('enter');void applyAudioPreferences(preferences,true);};
  const showModal=(modal:Parameters<typeof openModal>[0])=>{document.exitPointerLock?.();openModal(modal);if(modal==='add-site')completeOnboarding('add-site');if(modal==='customize-room')completeOnboarding('edit');playAudioCue('ui',preferences);};
  const showLauncher=()=>{document.exitPointerLock?.();setLauncher(true);completeOnboarding('quick-access');playAudioCue('ui',preferences);};
  const guidance=GUIDANCE.find(item=>!preferences.onboardingMilestones.includes(item.id));
  if(!ready)return <main className="grid h-dvh w-screen place-items-center bg-[#080913]"><div className="text-center"><span className="burrow-loader mx-auto mb-4 block h-11 w-11 rounded-2xl border border-violet-300/30 bg-violet-300/10"/><p className="mono text-[10px] uppercase tracking-[.25em] text-white/38">Opening your Burrow</p></div></main>;
  return <main className="relative h-dvh w-screen overflow-hidden bg-[#080913]">
    <div id="world-surface" className="absolute inset-0">{compactNotice?<div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,#252650,#080913_52%)]"/>:<Suspense fallback={<div className="grid h-full place-items-center text-xs text-white/35">Preparing the spatial Burrow…</div>}><BurrowWorld onLockChange={setLocked}/></Suspense>}</div>
    <header className="pointer-events-none absolute inset-x-0 top-0 z-10 flex items-start justify-between gap-3 p-4 md:p-6"><button onClick={()=>showModal('data')} className="glass pointer-events-auto flex items-center gap-3 rounded-2xl px-3 py-2.5 text-left transition hover:-translate-y-0.5 md:px-4 md:py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-400/15 text-violet-200"><Diamond size={19}/></span><span className="min-w-0"><span className="block text-[9px] font-semibold uppercase tracking-[.22em] text-violet-200/55">WebBurrow <span className="text-white/24">1.0.0</span></span><span className="block max-w-36 truncate text-sm font-medium">{currentRoom?.name}</span></span></button><nav className="pointer-events-auto flex gap-2" aria-label="Primary actions"><button onClick={()=>showModal('add-site')} className="hud-button" aria-label="Add website"><Plus size={17}/><span className="hidden lg:inline">Add site</span></button><button onClick={showLauncher} className="hud-button" aria-label="Open Quick Access"><Search size={17}/><span className="hidden sm:inline">Quick Access</span><kbd className="mono hidden rounded bg-white/8 px-1.5 py-0.5 text-[9px] text-white/42 md:inline">Ctrl K</kbd></button><button onClick={()=>{document.exitPointerLock?.();setEditMode(!editMode);completeOnboarding('edit');playAudioCue('ui',preferences);}} className={`hud-button ${editMode?'!border-cyan-200/40 !bg-cyan-200/10 text-cyan-100':''}`} aria-pressed={editMode}><Edit3 size={17}/><span className="hidden xl:inline">Edit</span></button><button onClick={()=>showModal('help')} className="hud-button" aria-label="Help"><HelpCircle size={17}/></button></nav></header>

    {!preferences.hasEntered&&!editMode&&<div className="pointer-events-none fixed inset-0 z-20 grid place-items-center p-4"><section className="glass onboarding-card pointer-events-auto w-full max-w-[420px] rounded-[28px] p-7 text-center"><span className="mx-auto mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-200"><Sparkles size={20}/></span><p className="mono mb-2 text-[9px] uppercase tracking-[.24em] text-cyan-200/70">Your internet is a place</p><h1 className="m-0 text-3xl font-semibold tracking-[-.045em]">Enter your {currentRoom?.name||'Burrow'}</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-white/57">Start spatially or stay in the fast HTML interface. Guidance appears one small step at a time and can always be dismissed.</p><button id="explore-trigger" onClick={enter} className="mt-6 rounded-xl bg-[#ddd6ff] px-5 py-3 text-sm font-semibold text-[#171529] shadow-[0_8px_30px_rgba(139,117,255,.28)]">Enter spatial view</button><button onClick={useInterface} className="ml-2 mt-4 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/56">Use quick controls</button><p className="mono mt-5 text-[9px] uppercase tracking-wider text-white/30">Local-first · sound remains off · no account</p></section></div>}
    {preferences.hasEntered&&guidance&&!editMode&&!compactNotice&&<aside className="glass absolute left-5 top-24 z-[12] w-[min(330px,calc(100%-40px))] rounded-2xl p-4"><header className="flex items-start gap-3"><span className="mono rounded-lg bg-cyan-200/10 px-2 py-1 text-[9px] text-cyan-100">{guidance.key}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{guidance.title}</p><p className="mt-1 text-xs leading-5 text-white/46">{guidance.body}</p></div><button onClick={()=>completeOnboarding(guidance.id)} aria-label={`Dismiss ${guidance.title}`} className="text-white/32 hover:text-white"><X size={14}/></button></header><button onClick={()=>completeOnboarding(guidance.id)} className="mt-3 text-[10px] font-medium text-cyan-200">Got it · show the next tip</button></aside>}

    {locked&&!editMode&&<div className="pointer-events-none absolute left-1/2 top-1/2 h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/70 bg-white/15 shadow-[0_0_10px_rgba(139,230,255,.7)]"/>}
    {!editMode&&preferences.hasEntered&&<div className={`interaction-prompt pointer-events-none absolute bottom-6 left-1/2 z-10 flex -translate-x-1/2 items-center gap-2 rounded-full px-4 py-2 text-xs glass ${nearId?'is-active':''}`}><Compass size={14} className="text-cyan-200"/><span>{nearId==='__portal'?'Ride the Burrow Lift':nearId==='__notes'?'Open your pocket note':nearId==='__favorites'?'Browse your whole Burrow':nearId?.startsWith('__live:')?'Inspect this live surface':nearObject?`Open ${nearObject.name}`:'Face an object to interact'}</span>{nearId&&<span className="mono ml-2 rounded bg-white/10 px-2 py-1 text-[10px]">E</span>}</div>}
    {arrival&&<div className="arrival-card pointer-events-none absolute inset-0 z-[9] grid place-items-center"><div className="text-center"><p className="mono text-[9px] uppercase tracking-[.3em] text-cyan-200/60">Burrow Lift</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em]">{arrival}</p></div></div>}
    <button onClick={returnToSpawn} className="glass absolute bottom-6 left-6 z-10 hidden items-center gap-2 rounded-xl px-3 py-2 text-xs text-white/48 md:flex" title="Return to a safe spot (Home key)"><RotateCcw size={13}/>Safe spot</button>
    <EditPanel/><BurrowTray/><CommandLauncher/><ModalLayer/>
    {toast&&<div role="status" className="toast glass absolute left-1/2 top-24 z-50 -translate-x-1/2 rounded-xl px-4 py-2.5 text-sm shadow-xl">{toast}</div>}
    {compactNotice&&<section className="glass absolute inset-x-3 top-[108px] z-[8] rounded-3xl p-5 md:hidden"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="mono text-[9px] uppercase tracking-[.2em] text-cyan-200/60">Companion layout</p><h2 className="mt-1 text-xl font-semibold">Your digital home, within reach</h2><p className="mt-2 text-xs leading-5 text-white/48">Mini Burrow, search, rooms, notes, and live cards stay available without first-person controls.</p></div><button onClick={()=>setCompactNotice(false)} aria-label="Try spatial view"><X size={15}/></button></div><div className="mt-4 grid grid-cols-2 gap-2"><button className="rounded-xl border border-white/9 bg-white/5 p-3 text-left text-sm" onClick={showLauncher}><Search size={16} className="mb-2 text-cyan-200"/>Quick Access</button><button className="rounded-xl border border-white/9 bg-white/5 p-3 text-left text-sm" onClick={()=>setTrayOpen(true)}><Compass size={16} className="mb-2 text-violet-200"/>Mini Burrow</button>{rooms.slice(0,4).map(room=><button key={room.id} className="truncate rounded-xl border border-white/9 bg-white/[.035] p-3 text-left text-xs" onClick={()=>setCurrentRoom(room.id)}><span className="mr-2 inline-block h-2 w-2 rounded-full" style={{background:room.accent}}/>{room.name}</button>)}</div></section>}
  </main>;
}
