import type { Preferences } from './types';

type Cue='ui'|'open'|'portal'|'interaction';
let context:AudioContext|undefined;let master:GainNode|undefined;let ambience:OscillatorNode|undefined;let ambienceGain:GainNode|undefined;

function ensureContext(){if(typeof window==='undefined'||!('AudioContext'in window))return undefined;if(!context){context=new AudioContext();master=context.createGain();master.gain.value=0;master.connect(context.destination);}return context;}
function stopAmbience(){try{ambience?.stop();}catch{}ambience?.disconnect();ambienceGain?.disconnect();ambience=undefined;ambienceGain=undefined;}
function syncAmbience(preferences:Pick<Preferences,'soundEnabled'|'soundVolume'|'ambienceEnabled'>){if(!context||!master)return;if(!preferences.soundEnabled||!preferences.ambienceEnabled||document.hidden){stopAmbience();return;}if(ambience)return;ambience=context.createOscillator();ambience.type='sine';ambience.frequency.value=54;ambienceGain=context.createGain();ambienceGain.gain.value=.018;ambience.connect(ambienceGain).connect(master);ambience.start();}

export async function applyAudioPreferences(preferences:Pick<Preferences,'soundEnabled'|'soundVolume'|'ambienceEnabled'>,userGesture=false){if(!preferences.soundEnabled){if(master)master.gain.value=0;stopAmbience();return;}if(!userGesture&&!context)return;const audio=ensureContext();if(!audio||!master)return;if(userGesture&&audio.state==='suspended')await audio.resume();master.gain.setTargetAtTime(preferences.soundVolume,audio.currentTime,.025);syncAmbience(preferences);}
export function playAudioCue(cue:Cue,preferences:Pick<Preferences,'soundEnabled'|'soundVolume'|'ambienceEnabled'>){if(!preferences.soundEnabled||!context||!master||context.state!=='running'||document.hidden)return;const oscillator=context.createOscillator(),gain=context.createGain(),now=context.currentTime;const values:Record<Cue,[number,number,OscillatorType]>={ui:[420,.045,'sine'],open:[610,.1,'triangle'],portal:[220,.22,'sine'],interaction:[520,.07,'triangle']};const[frequency,duration,type]=values[cue];oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,now);oscillator.frequency.exponentialRampToValueAtTime(frequency*(cue==='portal'?1.65:1.12),now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.06,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);oscillator.connect(gain).connect(master);oscillator.start(now);oscillator.stop(now+duration+.02);}
export function handleAudioVisibility(preferences:Pick<Preferences,'soundEnabled'|'soundVolume'|'ambienceEnabled'>){if(document.hidden)stopAmbience();else syncAmbience(preferences);}
